import { Product, User } from '../types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Maize Flour - Sifted',
    description: 'Premium quality sifted maize flour, perfect for ugali and other traditional Kenyan dishes.',
    categoryId: 'cat-1',
    category: { id: 'cat-1', name: 'Grains & Cereals', isActive: true, createdAt: new Date(), updatedAt: new Date() },
    costPrice: 110,
    retailPrice: 120,
    wholesalePrice: 115,
    stockQuantity: 500,
    minStockLevel: 50,
    maxStockLevel: 1000,
    vatStatus: 'INCLUSIVE' as const,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Rice - Pishori Grade A',
    description: 'Authentic Pishori rice from Mwea. Aromatic and perfect for pilau, biryani, and everyday meals.',
    categoryId: 'cat-1',
    category: { id: 'cat-1', name: 'Grains & Cereals', isActive: true, createdAt: new Date(), updatedAt: new Date() },
    costPrice: 170,
    retailPrice: 180,
    wholesalePrice: 175,
    stockQuantity: 300,
    minStockLevel: 30,
    maxStockLevel: 800,
    vatStatus: 'INCLUSIVE' as const,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Cooking Oil - 5L',
    description: 'Pure vegetable cooking oil. Ideal for frying and cooking. Cholesterol-free.',
    categoryId: 'cat-2',
    category: { id: 'cat-2', name: 'Cooking Essentials', isActive: true, createdAt: new Date(), updatedAt: new Date() },
    costPrice: 1100,
    retailPrice: 1200,
    wholesalePrice: 1150,
    stockQuantity: 200,
    minStockLevel: 20,
    maxStockLevel: 500,
    vatStatus: 'INCLUSIVE' as const,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'Sugar - White Refined',
    description: 'Pure white refined sugar. Perfect for tea, baking, and general use.',
    categoryId: 'cat-3',
    category: { id: 'cat-3', name: 'Sugar & Sweeteners', isActive: true, createdAt: new Date(), updatedAt: new Date() },
    costPrice: 140,
    retailPrice: 150,
    wholesalePrice: 145,
    stockQuantity: 600,
    minStockLevel: 60,
    maxStockLevel: 1200,
    vatStatus: 'INCLUSIVE' as const,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1582169296194-e4d644c48063?w=400',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: 'Wheat Flour - Baker\'s Choice',
    description: 'High-quality wheat flour for baking bread, chapati, and pastries.',
    categoryId: 'cat-1',
    category: { id: 'cat-1', name: 'Grains & Cereals', isActive: true, createdAt: new Date(), updatedAt: new Date() },
    costPrice: 125,
    retailPrice: 135,
    wholesalePrice: 130,
    stockQuantity: 400,
    minStockLevel: 40,
    maxStockLevel: 800,
    vatStatus: 'INCLUSIVE' as const,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1628173925278-46e5ae8a26a4?w=400',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '6',
    name: 'Tea Leaves - Kenya AA',
    description: 'Premium Kenya AA tea leaves. Rich flavor and aroma.',
    categoryId: 'cat-4',
    category: { id: 'cat-4', name: 'Beverages', isActive: true, createdAt: new Date(), updatedAt: new Date() },
    costPrice: 230,
    retailPrice: 250,
    wholesalePrice: 240,
    stockQuantity: 150,
    minStockLevel: 15,
    maxStockLevel: 300,
    vatStatus: 'INCLUSIVE' as const,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '7',
    name: 'Beans - Red Kidney',
    description: 'High-quality red kidney beans. Rich in protein and fiber.',
    categoryId: 'cat-5',
    category: { id: 'cat-5', name: 'Legumes', isActive: true, createdAt: new Date(), updatedAt: new Date() },
    costPrice: 150,
    retailPrice: 160,
    wholesalePrice: 155,
    stockQuantity: 350,
    minStockLevel: 35,
    maxStockLevel: 700,
    vatStatus: 'INCLUSIVE' as const,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1589994965851-a8f479c573a9?w=400',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '8',
    name: 'Salt - Iodized',
    description: 'Iodized table salt. Essential for healthy cooking.',
    categoryId: 'cat-6',
    category: { id: 'cat-6', name: 'Spices & Seasonings', isActive: true, createdAt: new Date(), updatedAt: new Date() },
    costPrice: 40,
    retailPrice: 45,
    wholesalePrice: 42,
    stockQuantity: 800,
    minStockLevel: 80,
    maxStockLevel: 1600,
    vatStatus: 'INCLUSIVE' as const,
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1587281524116-e2d7f1f50679?w=400',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockUser: User = {
  id: '1',
  clerkId: 'mock-clerk-id',
  email: 'customer@example.com',
  firstName: 'John',
  lastName: 'Mwangi',
  role: 'ADMIN' as const,
  isActive: true,
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const categories = [
  'All Categories',
  'Grains & Cereals',
  'Cooking Essentials',
  'Sugar & Sweeteners',
  'Beverages',
  'Legumes',
  'Spices & Seasonings',
];
