import { Product, User } from '../types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Maize Flour - Sifted',
    description: 'Premium quality sifted maize flour, perfect for ugali and other traditional Kenyan dishes.',
    category: 'Grains & Cereals',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    basePrice: 120,
    stock: 500,
    packaging: [
      { type: 'CARTON', unitsPerPackage: 20, pricePerPackage: 2200 },
      { type: 'BALE', unitsPerPackage: 10, pricePerPackage: 1150 },
      { type: 'SINGLE', unitsPerPackage: 1, pricePerPackage: 120 },
    ],
    supplierName: 'Unga Ltd',
    featured: true,
  },
  {
    id: '2',
    name: 'Rice - Pishori Grade A',
    description: 'Authentic Pishori rice from Mwea. Aromatic and perfect for pilau, biryani, and everyday meals.',
    category: 'Grains & Cereals',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    basePrice: 180,
    stock: 300,
    packaging: [
      { type: 'CARTON', unitsPerPackage: 12, pricePerPackage: 2050 },
      { type: 'BALE', unitsPerPackage: 6, pricePerPackage: 1050 },
      { type: 'SINGLE', unitsPerPackage: 1, pricePerPackage: 180 },
    ],
    supplierName: 'Mwea Rice Ltd',
    featured: true,
  },
  {
    id: '3',
    name: 'Cooking Oil - 5L',
    description: 'Pure vegetable cooking oil. Ideal for frying and cooking. Cholesterol-free.',
    category: 'Cooking Essentials',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400',
    basePrice: 1200,
    stock: 200,
    packaging: [
      { type: 'CARTON', unitsPerPackage: 4, pricePerPackage: 4650 },
      { type: 'SINGLE', unitsPerPackage: 1, pricePerPackage: 1200 },
    ],
    supplierName: 'Pwani Oil',
    featured: true,
  },
  {
    id: '4',
    name: 'Sugar - White Refined',
    description: 'Pure white refined sugar. Perfect for tea, baking, and general use.',
    category: 'Sugar & Sweeteners',
    image: 'https://images.unsplash.com/photo-1582169296194-e4d644c48063?w=400',
    basePrice: 150,
    stock: 600,
    packaging: [
      { type: 'CARTON', unitsPerPackage: 10, pricePerPackage: 1450 },
      { type: 'BALE', unitsPerPackage: 20, pricePerPackage: 2850 },
      { type: 'SINGLE', unitsPerPackage: 1, pricePerPackage: 150 },
    ],
    supplierName: 'Mumias Sugar',
    featured: false,
  },
  {
    id: '5',
    name: 'Wheat Flour - Baker\'s Choice',
    description: 'High-quality wheat flour for baking bread, chapati, and pastries.',
    category: 'Grains & Cereals',
    image: 'https://images.unsplash.com/photo-1628173925278-46e5ae8a26a4?w=400',
    basePrice: 135,
    stock: 400,
    packaging: [
      { type: 'CARTON', unitsPerPackage: 12, pricePerPackage: 1550 },
      { type: 'BALE', unitsPerPackage: 6, pricePerPackage: 790 },
      { type: 'SINGLE', unitsPerPackage: 1, pricePerPackage: 135 },
    ],
    supplierName: 'Pembe Flour Mills',
    featured: true,
  },
  {
    id: '6',
    name: 'Tea Leaves - Kenya AA',
    description: 'Premium Kenya AA tea leaves. Rich flavor and aroma.',
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400',
    basePrice: 250,
    stock: 150,
    packaging: [
      { type: 'CARTON', unitsPerPackage: 24, pricePerPackage: 5800 },
      { type: 'OUTER', unitsPerPackage: 12, pricePerPackage: 2950 },
      { type: 'SINGLE', unitsPerPackage: 1, pricePerPackage: 250 },
    ],
    supplierName: 'Kenya Tea Packers',
    featured: false,
  },
  {
    id: '7',
    name: 'Beans - Red Kidney',
    description: 'High-quality red kidney beans. Rich in protein and fiber.',
    category: 'Legumes',
    image: 'https://images.unsplash.com/photo-1589994965851-a8f479c573a9?w=400',
    basePrice: 160,
    stock: 350,
    packaging: [
      { type: 'CARTON', unitsPerPackage: 10, pricePerPackage: 1550 },
      { type: 'BALE', unitsPerPackage: 5, pricePerPackage: 780 },
      { type: 'SINGLE', unitsPerPackage: 1, pricePerPackage: 160 },
    ],
    supplierName: 'Rift Valley Grains',
    featured: false,
  },
  {
    id: '8',
    name: 'Salt - Iodized',
    description: 'Iodized table salt. Essential for healthy cooking.',
    category: 'Spices & Seasonings',
    image: 'https://images.unsplash.com/photo-1587281524116-e2d7f1f50679?w=400',
    basePrice: 45,
    stock: 800,
    packaging: [
      { type: 'CARTON', unitsPerPackage: 50, pricePerPackage: 2150 },
      { type: 'OUTER', unitsPerPackage: 25, pricePerPackage: 1100 },
      { type: 'SINGLE', unitsPerPackage: 1, pricePerPackage: 45 },
    ],
    supplierName: 'Krystalline Salt',
    featured: false,
  },
];

export const mockUser: User = {
  id: '1',
  email: 'customer@example.com',
  name: 'John Mwangi',
  phone: '+254712345678',
  role: 'CUSTOMER',
  county: 'Nairobi',
  town: 'Westlands',
  mpesaPhone: '254712345678',
};

export const categories = [
  'All Categories',
  'Grains & Cereals',
  'Cooking Essentials',
  'Sugar & Sweeteners',
  'Beverages',
  'Legumes',
  'Spices & Seasonings',
];
